# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disruption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('line', models.IntegerField()),
                ('toStation', models.IntegerField()),
                ('fromStation', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
